# Generated by Django 2.2.4 on 2020-11-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message1', to='login_reg_app.Users'),
        ),
    ]
