# Generated by Django 2.2.4 on 2020-11-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
